#!/usr/bin/env python3
import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args():
    p = argparse.ArgumentParser(description="Plot telemetry CSV generated by serial_logger.py")
    p.add_argument("--in", dest="csv_path", required=True, help="Input CSV file")
    p.add_argument("--out-dir", default="plots", help="Directory to save PNG plots")
    p.add_argument("--show", action="store_true", help="Show plots on screen")
    return p.parse_args()


def load_dataframe(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    if df.empty:
        raise ValueError("CSV is empty")

    numeric_cols = [
        "mcu_time_ms",
        "rpm1_x10",
        "rpm2_x10",
        "rpm3_x10",
        "rpm4_x10",
        "battery_mV",
        "battery_adc",
        "cmd1",
        "cmd2",
        "cmd3",
        "cmd4",
        "brake",
    ]
    for c in numeric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    df = df.dropna(subset=["mcu_time_ms"]).copy()
    df["t_s"] = (df["mcu_time_ms"] - df["mcu_time_ms"].iloc[0]) / 1000.0
    for i in range(1, 5):
        df[f"rpm{i}"] = df[f"rpm{i}_x10"] / 10.0
    df["battery_v"] = df["battery_mV"] / 1000.0
    return df


def save_plot(path: Path, title: str, ylabel: str, x, ys, labels):
    plt.figure(figsize=(12, 5))
    for y, label in zip(ys, labels):
        plt.plot(x, y, label=label, linewidth=1.2)
    plt.title(title)
    plt.xlabel("Time [s]")
    plt.ylabel(ylabel)
    plt.grid(True, alpha=0.3)
    plt.legend(loc="best")
    plt.tight_layout()
    plt.savefig(path, dpi=140)
    plt.close()


def main():
    args = parse_args()
    csv_path = Path(args.csv_path)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = load_dataframe(csv_path)
    t = df["t_s"]

    save_plot(
        out_dir / "rpm.png",
        "Motor Speed (RPM)",
        "RPM",
        t,
        [df["rpm1"], df["rpm2"], df["rpm3"], df["rpm4"]],
        ["rpm1", "rpm2", "rpm3", "rpm4"],
    )

    save_plot(
        out_dir / "cmd.png",
        "Motor Commands",
        "CMD",
        t,
        [df["cmd1"], df["cmd2"], df["cmd3"], df["cmd4"]],
        ["cmd1", "cmd2", "cmd3", "cmd4"],
    )

    save_plot(
        out_dir / "battery.png",
        "Battery Voltage",
        "Voltage [V]",
        t,
        [df["battery_v"]],
        ["battery_v"],
    )

    save_plot(
        out_dir / "rpm_vs_cmd_m1.png",
        "Motor 1: RPM vs CMD",
        "Value",
        t,
        [df["rpm1"], df["cmd1"]],
        ["rpm1", "cmd1"],
    )

    print(f"Rows: {len(df)}")
    print(f"Saved: {out_dir / 'rpm.png'}")
    print(f"Saved: {out_dir / 'cmd.png'}")
    print(f"Saved: {out_dir / 'battery.png'}")
    print(f"Saved: {out_dir / 'rpm_vs_cmd_m1.png'}")

    if args.show:
        fig, axes = plt.subplots(3, 1, figsize=(12, 9), sharex=True)
        axes[0].plot(t, df["rpm1"], label="rpm1")
        axes[0].plot(t, df["rpm2"], label="rpm2")
        axes[0].plot(t, df["rpm3"], label="rpm3")
        axes[0].plot(t, df["rpm4"], label="rpm4")
        axes[0].set_ylabel("RPM")
        axes[0].grid(True, alpha=0.3)
        axes[0].legend(loc="best")

        axes[1].plot(t, df["cmd1"], label="cmd1")
        axes[1].plot(t, df["cmd2"], label="cmd2")
        axes[1].plot(t, df["cmd3"], label="cmd3")
        axes[1].plot(t, df["cmd4"], label="cmd4")
        axes[1].set_ylabel("CMD")
        axes[1].grid(True, alpha=0.3)
        axes[1].legend(loc="best")

        axes[2].plot(t, df["battery_v"], label="battery_v")
        axes[2].set_xlabel("Time [s]")
        axes[2].set_ylabel("V")
        axes[2].grid(True, alpha=0.3)
        axes[2].legend(loc="best")

        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    main()

