[env:esp32dev]

platform = platformio/espressif32
board = esp32dev
framework = espidf

monitor_speed = 115200
upload_speed = 115200

board_upload.flash_size = 2MB
board_upload.maximum_size = 2097152

extra_scripts = pre:scripts/generate_web_assets.py

build_flags =
    -Wall
    -Wextra
    -I.pio/generated
